base:
  random_state: 42
  log_level: INFO

data:
  # loading data
  datasets : "./data/raw/Diabete.csv"
  split_ratio : 0.3

preprocess:
  # preprocessing data
  scaler : "StandardScaler"
  normalize : "PowerTransformer"



train:
  clf_params:
    "c":0.002
    "solver":"lbfgs"
    "multi_class":"auto"
    "max_iter":100

  target_col: "class"

evaluate:
  # evaluating model

path:
  xtrain_path: "./data/processed/xtrain.csv"
  xtest_path: "./data/processed/xtest.csv"
  ytrain_path: "./data/processed/ytrain.csv"
  ytest_path: "./data/processed/ytest.csv"
  model_path: "./models/model.joblib"
  metrics_path: "./report/metrics.json"
  conf_matrix_path: "./report/confusion_matrix.png"
  final_data_path: "./data/final/"