base:
  random_state: 42
  log_level: INFO

data:
  # loading data
  datasets: "./data/raw/Diabete.csv"
  split_ratio: 0.3

preprocess:
  # preprocessing data
  scaler: "StandardScaler"
  normalize: "PowerTransformer"

train:
  log_reg:
    params:
      C: [0.002, 0.001, 0.01, 0.004]
      solver: ["lbfgs"]
      multi_class: ["auto"]
      max_iter: [100, 200, 300, 400, 500]
    name: "LogRe"

  random_forest:
    params:
      n_estimators: [100, 200, 300, 400, 500]
      max_depth: [5, 10, 15, 20, 25]
      min_samples_split: [2, 3, 4, 5]
      min_samples_leaf: [1, 2, 3, 4, 5]
      max_features: ["auto", "sqrt", "log2"]
      max_leaf_nodes: [None, 2, 3, 4, 5]
    name: "RandomForest"

  svm:
    params:
      C: [0.002, 0.001, 0.01, 0.004]
      kernel: ["linear", "poly", "rbf", "sigmoid"]
      degree: [2, 3, 4, 5]
      gamma: ["scale", "auto"]
    name: "svm"

  knn:
    params:
      n_neighbors: [3, 4, 5, 6, 7]
      weights: ["uniform", "distance"]
      algorithm: ["auto", "ball_tree", "kd_tree", "brute"]
      leaf_size: [10, 20, 30, 40, 50]
      metric: ["euclidean", "manhattan", "minkowski"]
    name: "knn"

  target_col: "CLASS"
  drop_cols: ["ID"]

evaluate:
  # evaluating model

path:
  xtrain_path: "./data/processed/xtrain.csv"
  xtest_path: "./data/processed/xtest.csv"
  ytrain_path: "./data/processed/ytrain.csv"
  ytest_path: "./data/processed/ytest.csv"
  model_path: "./models/model.joblib"
  metrics_path: "./report/metrics.json"
  conf_matrix_path: "./report/confusion_matrix.png"
  final_data_path: "./data/final/"
  tranform_path: "./data_trans_pipiline/transformation.joblib"
